version: "3.9"
services:
  db:
    image: postgres:16
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrator:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: -path=/migrations -database postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable up
  app:
    image: antgoncharik/crypto-knight-api
    env_file:
      - .env
    restart: always
    volumes:
      - .env:/app/.env:ro
      - ./config/rsa:/app/config/rsa:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "10.10.0.3:8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 15s
      timeout: 3s
      retries: 3
volumes:
  db_data: