ALTER TABLE tracks ADD COLUMN high_price_1 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN high_price_2 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN high_price_3 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN low_price_1 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN low_price_2 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN low_price_3 NUMERIC NOT NULL DEFAULT 0;
