ALTER TABLE tracks ADD COLUMN resistance_price_1 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN support_price_1 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN resistance_price_2 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN support_price_2 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN resistance_price_3 NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN support_price_3 NUMERIC NOT NULL DEFAULT 0;
