CREATE TABLE IF NOT EXISTS last_entries (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    high_price NUMERIC NOT NULL DEFAULT 0,
    low_price NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);